---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags: variables

# Setup/install tasks.
- name: for OS
  include_tasks: "setup-{{ ansible_os_family }}.yml"
  tags: setup

# Configuration/reload tasks.
- name: for OS
  include_tasks: "config-{{ ansible_os_family }}.yml"
  tags: config