---

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install a list of packages
  apt:
    pkg:
    - wget
    - gnupg2
    - lsb-release
    - curl
    - python3-pip # for module community sql
    state: present

- name: Fetch the repository packages from Percona web
  get_url:
    url: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
    dest: /opt/percona-release_latest.generic_all.deb
    mode: '0440'

- name: Install the downloaded package with dpkg
  shell: |
    dpkg -i /opt/percona-release_latest.generic_all.deb
    pip3 install pymysql

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Setup Root pwd cluster
  shell: |
    echo "percona-xtradb-cluster-server-5.6 percona-xtradb-cluster-server/root_password password {{pxc_root_pwd}}" | sudo debconf-set-selections
    echo "percona-xtradb-cluster-server-5.6 percona-xtradb-cluster-server/root_password_again password {{pxc_root_pwd}}" | sudo debconf-set-selections

- name: Ensure percona-xtra-db-cluster
  apt:
    name: "{{pxc_package_name}}"
    state: present

# - name: debug
#   ansible.builtin.debug:
#     msg:
#       - "SHOW DEBUG: {{ node_ips_self_exclude }}"
#       - "SHOW DEBUG: {{ ansible_host }}"
#       - "SHOW DEBUG: {{ inventory_hostname }}"
      
